# Application Name
spring.application.name=Rev Aux


# Default Profile (Can be overridden)
spring.profiles.active=dev  

# Common JPA settings (applied to all profiles)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Default Server Port (Will be overridden per profile)
server.port=8080

# Set Application Context Path
server.servlet.context-path=/rev-aux


# Default Logging Level
logging.level.org.springframework=INFO

spring.data.redis.host=localhost
spring.data.redis.port=6379

#logging.level.org.springframework.web=DEBUG
#logging.level.org.thymeleaf=DEBUG


# Set max file size to 100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB



