# Database Configuration (Same Across All Profiles)
spring.datasource.url=jdbc:postgresql://192.168.1.203:5432/sk-test-without-jhip-arc
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Production Server Port
server.port=8080  

# Production Logging Level
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR


# Disable Hibernate Schema Changes in Production
spring.jpa.hibernate.ddl-auto=validate
