# Database Configuration (Same Across All Profiles)
spring.datasource.url=jdbc:postgresql://192.168.1.203:5432/sk-test-without-jhip-arc
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver



# Testing Logging Level
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

