# Database Configuration (Same Across All Profiles)

#spring.datasource.url=jdbc:postgresql://192.168.1.203:5432/cps_db_20022025
spring.datasource.url=jdbc:postgresql://localhost:5432/cps_db_08032025
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Development Server Port
server.port=8080

# Development Logging Level
logging.level.org.springframework=INFO


